name: Node.js Tests

on:
  push:
    branches-ignore:
    - 'master'

jobs:
  Validate:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
    - name: Install
      if: steps.Cache.outputs.cache-hit != 'true'
      run: npm i
    - name: Build and test
      run: npm start validate
